### ISSUE TITLE
ImportError: cannot import name parse_url

### ISSUE THREAD

**Issue by RC1234** [rllynch/pi_garage_alert#6]
I am setting up a new Raspberry Pi 3

When I try to run:
sudo /usr/local/sbin/pi_garage_alert.py
I get the following error: 

pi@raspberrypi:~ $ sudo /usr/local/sbin/pi_garage_alert.py
Traceback (most recent call last):
  File "/usr/local/sbin/pi_garage_alert.py", line 59, in <module>
    from slackclient import SlackClient
  File "/usr/local/lib/python2.7/dist-packages/slackclient/__init__.py", line 1, in <module>
    from slackclient._client import SlackClient  # noqa
  File "/usr/local/lib/python2.7/dist-packages/slackclient/_client.py", line 6, in <module>
    from slackclient._server import Server
  File "/usr/local/lib/python2.7/dist-packages/slackclient/_server.py", line 2, in <module>
    from requests.packages.urllib3.util.url import parse_url
**ImportError: cannot import name parse_url**

**Comment by gfxslax** [comment]
Getting same error on the pi zero, any help would be greatly appreciated

**Comment by rllynch** [comment]
Issuing the following command should fix it:

sudo pip install -U requests

**Comment by gfxslax** [comment]
command returns:

pi@raspberrypi:~ $ sudo pip install -U requests
Downloading/unpacking requests from https://pypi.python.org/packages/5a/58/671011e3ff4a06e2969322267d78dcfda1bf4d1576551df1cce93cd7239d/requests-2.18.1-py2.py3-none-any.whl#md5=a7fbdc82134a2610b3d0cdc7e59f0bde
  Downloading requests-2.18.1-py2.py3-none-any.whl (88kB): 88kB downloaded
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests)
Downloading/unpacking urllib3>=1.21.1,<1.22 (from requests)
  Downloading urllib3-1.21.1-py2.py3-none-any.whl (131kB): 131kB downloaded
Downloading/unpacking chardet>=3.0.2,<3.1.0 (from requests)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB): 133kB downloaded
Requirement already up-to-date: idna>=2.5,<2.6 in /usr/local/lib/python2.7/dist-packages (from requests)
Installing collected packages: requests, urllib3, chardet
  Found existing installation: requests 2.4.3
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: urllib3 1.9.1
    Not uninstalling urllib3 at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: chardet 2.3.0
    Not uninstalling chardet at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed requests urllib3 chardet
Cleaning up...

but still getting same cannot import error.
thanks again for the help!

**Comment by rllynch** [comment]
Odd, works for me on a fresh install.  Does "pip show requests" report version 2.18.1, or is it reporting the older 2.4.3 version?

**Comment by gfxslax** [comment]
pi@raspberrypi:~ $ pip show requests
---
Name: requests
Version: 2.4.3
Location: /usr/lib/python2.7/dist-packages
Requires: 

yup its giving 2.4.3

**Comment by gfxslax** [comment]
ok got it, did a "sudo apt-get remove python-pip", then a "sudo easy_install pip", and then finally did the "sudo pip install -U requests"
works like a charm now! Thanks!!

**Comment by RC1234** [comment]
THANK YOU RICH!!!    
sudo pip install -U requests
Worked perfectly for me!  Thanks again for this great garage door alert.
